### PR TITLE
Image labels

### PR DESCRIPTION
**Pull request by jimmyangel**
First, thank you for sharing this nice vue component.

Sometimes it is useful to have labels on the images. For example, if you are comparing the same aerial photo from two different time periods. I hope this PR is acceptable to you.

Best regards,

Ricardo

### CODE REVIEW

**Comment by junkboy0315** [comment]
@jimmyangel 
Hi! thanks for your contribution :)
If you can, could you exclude unnecesarry files?
I think including the following 2 files is enough.

- README.md
- src/VueCompareImage.vue

**Comment by jimmyangel** [comment]
Ok. I removed dist and package[-lock].json

**Comment by junkboy0315** [comment]
@jimmyangel 
Could you resolve conflictions?
Or I will do that myself if you don't mind.
(This PR will be closed and commits gonna be mine though)

**Comment by jimmyangel** [comment]
Go ahead, if you wish, otherwise, I can close this PR and open a new one. Let me know if you want me to do it.

**Comment by junkboy0315** [comment]
@jimmyangel 
Published as v0.2.0, Thanks 😄

**Comment by jimmyangel** [comment]
Cool, thank you!

**Pull request closed without merging**
